# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
language: objective-c

osx_image: xcode8.2

env:
  global:
    - PROJECT="Clappr.xcodeproj"
    - SCHEME="Clappr-Example"
    - DESTINATION="platform=iOS Simulator,name=iPhone 6s Plus,OS=10.0"

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform iOS
  - gem install cocoapods -v '1.1.1'
  - pod repo update

script:
  - pod lib lint
  - xcodebuild test -project "${PROJECT}" -scheme "${SCHEME}" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "${DESTINATION}" | xcpretty -s && exit ${PIPESTATUS[0]}
